### ISSUE TITLE
Anime Titles are being interpreted as AMAZON.NUMBER type

### ISSUE THREAD

**Issue by mistmurk** [mistmurk/giff-kawaii#2]
For anime titles such as "One Piece" or "One Punch Man", the voice interface will interpret the word "One" as the number literal "1". This makes it so that MAL is unable to find these anime.

**Comment by beForged** [comment]
https://www.thoughtco.com/how-to-convert-numbers-to-words-with-javascript-4072535

**Comment by beForged** [comment]
there is also an npm solution here although it may omit the 'and'
https://www.npmjs.com/package/number-to-words

**Comment by beForged** [comment]
should be fixed,
wrote a function that changes the inputted alexaString to words not digits
Testing needed
